Changed delay
blakeNaccarato/geldaq pull request #10
Opened 2023-01-05 20:09 UTC by asennain

2023-01-05 20:12 UTC, asennain commented
Related to issue #9

2023-01-06 20:17 UTC, blakeNaccarato requested changes
Here you can see how a Pull Request review works. I have commented on parts of your code and am recommending certain changes before we can merge this code.

2023-01-06 20:17 UTC, blakeNaccarato commented on src/geldaq/Abdul's Shenanigans/TestCodeJnotebook.ipynb
> +    "delay = 0.03\n",
Here's a toy example of how I might request changes to a section of your code. This is trivial, but perhaps you could change this delay to 0.05 instead?

2023-01-06 20:18 UTC, blakeNaccarato commented
Now that I have reviewed your work and requested changes as above, you can make further changes in the same branch (e.g. `Abdul_Changes`) and push them, then they will appear here and we can revisit the changes, and eventually merge.

2023-01-07 00:18 UTC, asennain commented on src/geldaq/Abdul's Shenanigans/TestCodeJnotebook.ipynb
> +    "delay = 0.03\n",
I don't know why but 0.05 sounds like a funny number. I don't like it.

2023-01-07 00:19 UTC, merged